version: '3'
services:
   server:
      container_name: cms-container
      restart: always
      build: .
      environment: 
         POSTGRES_DB: main
         POSTGRES_USER: user
         POSTGRES_PASSWORD: password
      ports:
         - '5000:4000'
      depends_on:
         - database
   database:
      image: postgres
      ports:
         - 5432:5432
      environment: 
         POSTGRES_DB: main
         POSTGRES_USER: user
         POSTGRES_PASSWORD: password
      volumes:
         - database-data:/var/lib/postgresql/data/
volumes:
  database-data: